const content=document.getElementById('panelContent'),overlay=document.getElementById('overlay');const views={
signup:`<span class="eyebrow">ابدأ رحلتك</span><h2>أنشئ حسابك</h2><p>خطوة واحدة تفصلك عن ملف مهني يفهمك فعلًا.</p><div class="form"><input placeholder="الاسم الكامل"><input placeholder="البريد الإلكتروني"><input type="password" placeholder="كلمة المرور"><button class="primary" onclick="openPanel('profile')">إنشاء الحساب ←</button></div>`,
profile:`<span class="eyebrow">ملفك المهني</span><h2>خلّينا نتعرّف عليك</h2><div class="form"><input placeholder="المدينة"><input placeholder="سنوات الخبرة"><select><option>المجال المطلوب</option><option>المبيعات</option><option>التسويق</option><option>الإدارة</option><option>التكنولوجيا</option></select><input placeholder="أهم مهاراتك"><button class="primary" onclick="openPanel('upload')">التالي</button></div>`,
upload:`<span class="eyebrow">تحليل السيرة الذاتية</span><h2>ارفع الـ CV</h2><div class="drop"><h3>اسحب الملف هنا أو اضغط للاختيار</h3><p>PDF, DOC, DOCX • حتى 5MB</p></div><br><button class="primary" onclick="openPanel('analysis')">تحليل السيرة الذاتية</button>`,
analysis:`<span class="eyebrow">الذكاء الاصطناعي يعمل الآن</span><h2>جاري تحليل سيرتك...</h2><p>✓ قراءة الخبرات والمهارات</p><p>✓ مقارنة متطلبات سوق العمل</p><p>✓ تحديد نقاط القوة والفجوات</p><button class="primary" onclick="openPanel('report')">عرض نتيجة العرض التجريبي</button>`,
report:`<span class="eyebrow">تقريرك الشخصي</span><h2>جاهزيتك لسوق العمل</h2><div class="score">78%</div><div class="miniCards"><div><b>نقاط القوة</b><p>المبيعات، العلاقات، قيادة الفريق</p></div><div><b>تحتاج تطوير</b><p>عرض الإنجازات، CRM، الإنجليزية المهنية</p></div><div><b>فرصتك الأسرع</b><p>Sales / Account Management</p></div></div><h3>ملاحظة من منهج مرام</h3><p>خبرتك أقوى مما يظهر في سيرتك الحالية. الأولوية ليست إضافة معلومات أكثر، بل تحويل مسؤولياتك إلى إنجازات واضحة وقابلة للقياس.</p><button class="primary" onclick="openPanel('plan')">ابنِ خطة تطويري</button>`,
plan:`<span class="eyebrow">خطة مخصصة</span><h2>خطتك للأسبوع القادم</h2><p>① إعادة صياغة 5 إنجازات في الـCV بالأرقام.</p><p>② تحديث LinkedIn بما يتوافق مع المسار المستهدف.</p><p>③ إكمال أساسيات CRM خلال 3 ساعات.</p><p>④ تدريب مقابلة لوظيفتين مستهدفتين.</p><p>⑤ التقديم على 5 فرص ذات تطابق مرتفع.</p><button class="primary" onclick="openPanel('advisor')">اسأل مستشار مرام</button>`,
advisor:`<span class="eyebrow">مستشار مرام الذكي</span><h2>شو حابب تعرف عن مسارك؟</h2><div class="chat"><div class="bubble me">حسب خبرتي، شو الوظائف الأنسب إلي؟</div><div class="bubble">بناءً على ملفك، أقرب المسارات لك هي Account Manager وSales Executive وBusiness Development. أنصحك تبدأ بالفرص التي تستفيد من خبرتك في العلاقات والمبيعات، وبنفس الوقت تقوي CRM وطريقة عرض إنجازاتك.</div></div><br><div class="form"><input placeholder="اكتب سؤالك هنا..."><button class="primary">إرسال</button></div>`,
jobs:`<span class="eyebrow">وظائف مناسبة لك</span><h2>الفرص الأعلى تطابقًا</h2><div class="job"><div><b>Sales Executive</b><small>رام الله • دوام كامل</small></div><strong>92%</strong></div><div class="job"><div><b>Account Manager</b><small>رام الله • شركة خدمات</small></div><strong>84%</strong></div><div class="job"><div><b>Business Development</b><small>Hybrid</small></div><strong>78%</strong></div>`,
company:`<span class="eyebrow">بوابة الشركات</span><h2>اعثر على المرشح الأنسب</h2><p>سجل شركتك، انشر الوظيفة، واستقبل قائمة مرشحين مرتبة حسب التطابق الفعلي مع احتياجك.</p><div class="form"><input placeholder="اسم الشركة"><input placeholder="البريد الإلكتروني للعمل"><input placeholder="المسمى الوظيفي المطلوب"><textarea placeholder="المهارات والخبرة المطلوبة"></textarea><button class="primary" onclick="openPanel('candidates')">نشر الوظيفة التجريبية</button></div>`,
admin:`<span class="eyebrow">لوحة إدارة مرام</span><h2>نظرة عامة على المنصة</h2><div class="miniCards"><div><b>1,284</b><p>باحث عن عمل</p></div><div><b>86</b><p>شركة</p></div><div><b>214</b><p>وظيفة نشطة</p></div></div><h3>إدارة المحتوى والمنهج</h3><p>من هنا تستطيع مرام إدارة الدورات، مراجعة الوظائف والشركات، متابعة تحليلات السير الذاتية، وتحديث قاعدة المعرفة التي يعتمد عليها المستشار الذكي.</p><div class="form"><button class="primary">المستخدمون وتحليلات CV</button><button class="secondary">الشركات والوظائف</button><button class="secondary">الدورات والمحتوى</button><button class="secondary">منهج مستشار مرام الذكي</button></div>`,candidates:`<span class="eyebrow">مرشحون مقترحون</span><h2>الأقرب لهذه الوظيفة</h2><div class="job"><div><b>أحمد محمود</b><small>5 سنوات • مبيعات B2B • CRM</small></div><strong>94%</strong></div><div class="job"><div><b>سارة خالد</b><small>4 سنوات • Account Management</small></div><strong>89%</strong></div><div class="job"><div><b>محمد علي</b><small>3 سنوات • Business Development</small></div><strong>82%</strong></div>`};function openPanel(v){content.innerHTML=views[v]||views.signup;overlay.classList.add('show')}function closePanel(){overlay.classList.remove('show')}document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel()});